name: foodzave
description: "Eine App zur Verwaltung von Lebensmitteln und Vermeidung von Verschwendung."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase Abhängigkeiten
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  # Barcode Scanning
  flutter_barcode_scanner: ^2.0.0
  # HTTP für API-Anfragen
  http: ^1.2.0
  # Lokale Datenspeicherung
  shared_preferences: ^2.2.2
  # Benachrichtigungen
  flutter_local_notifications: ^16.3.2
  # Formatierung und Lokalisierung
  intl: ^0.18.1
  # Teilen von Inhalten
  share_plus: ^11.0.0
  # State Management
  provider: ^6.0.5
  # Bildverwaltung
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  # Offline-Unterstützung
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
