// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqA3pHc4VRdjkTfDfCPTv25z4JE62j5CY',
    appId: '1:712792477015:web:b92df7b1bfdf7563268212',
    messagingSenderId: '712792477015',
    projectId: 'foodzave',
    authDomain: 'foodzave.firebaseapp.com',
    storageBucket: 'foodzave.firebasestorage.app',
    measurementId: 'G-J3EM16JMCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqJU2TC9v9_B_7O8rWmGeDOQSjFkNBZQ',
    appId: '1:712792477015:android:de6e5dfad40bba2c268212',
    messagingSenderId: '712792477015',
    projectId: 'foodzave',
    storageBucket: 'foodzave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmsEVcYKyBbanvA1e5zEhJ-ikKWVpE13w',
    appId: '1:712792477015:ios:7c35c59e1d19a05b268212',
    messagingSenderId: '712792477015',
    projectId: 'foodzave',
    storageBucket: 'foodzave.firebasestorage.app',
    iosBundleId: 'com.example.foodzave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmsEVcYKyBbanvA1e5zEhJ-ikKWVpE13w',
    appId: '1:712792477015:ios:7c35c59e1d19a05b268212',
    messagingSenderId: '712792477015',
    projectId: 'foodzave',
    storageBucket: 'foodzave.firebasestorage.app',
    iosBundleId: 'com.example.foodzave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqA3pHc4VRdjkTfDfCPTv25z4JE62j5CY',
    appId: '1:712792477015:web:fa77acba444add30268212',
    messagingSenderId: '712792477015',
    projectId: 'foodzave',
    authDomain: 'foodzave.firebaseapp.com',
    storageBucket: 'foodzave.firebasestorage.app',
    measurementId: 'G-CLRSC78NVE',
  );

}